package chavales.los.practica1android;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.os.Bundle;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class MainActivity extends AppCompatActivity {

    private RecyclerView lista;

    private static final Producto[] productos = {
            new Producto("Manzana con libros", "Apple", R.drawable.apple_256261_640, Calidad.BUENO, null, 73, Arrays.asList(new Producto.Detalle("Bajo en", Nutricion.FERTILIZANTE, 35.75f, Calidad.BUENO), new Producto.Detalle("Hasta arriba de", Nutricion.AZUCAR, 500, Calidad.MALO), new Producto.Detalle("Así asá de", Nutricion.PROTEINAS, 0.05f, Calidad.REGULAR), new Producto.Detalle("Un poquito de", Nutricion.TACOS, .5f, Calidad.BUENO), new Producto.Detalle("Bastantes ", Nutricion.NUECES, 30, Calidad.EXCELENTE))),
            new Producto("Frutas del bosque", "Mercadona", R.drawable.dark_mood_food_2986532_640, Calidad.MEDIOCRE, null, 23, Arrays.asList(new Producto.Detalle("Un par de", Nutricion.NUECES, 2, Calidad.MALO), new Producto.Detalle("Alto en", Nutricion.PROTEINAS, 23, Calidad.EXCELENTE), new Producto.Detalle("Moderada", Nutricion.ENERGIA, 1500, Calidad.BUENO), new Producto.Detalle("Un poco de", Nutricion.SODIO, 9, Calidad.BUENO))),
            new Producto("Ingredientes para pasta", "Samsung", R.drawable.food_1932466_640, Calidad.EXCELENTE, null, 91, Arrays.asList(new Producto.Detalle("Alto en", Nutricion.AZUCAR, 100, Calidad.MEDIOCRE), new Producto.Detalle("Alto en", Nutricion.SODIO, 1290, Calidad.MALO), new Producto.Detalle("Algo de", Nutricion.AMIANTO, 0.02f, Calidad.BUENO))),
            new Producto("Tabla embutido", "Lidl", R.drawable.food_platter_2175326_640, Calidad.REGULAR, null, 49, Arrays.asList(new Producto.Detalle("Moderados", Nutricion.TACOS, 10, Calidad.EXCELENTE), new Producto.Detalle("Moderadamente", Nutricion.RAMEN, 1.6729f, Calidad.REGULAR), new Producto.Detalle("Moderados", Nutricion.NUECES, .77f, Calidad.MEDIOCRE), new Producto.Detalle("Una cantidad de", Nutricion.GASOLINA, 995, Calidad.BUENO))),
            new Producto("Ositos gominolas", "Haribo", R.drawable.gummibarchen_318362_640, Calidad.BUENO, null, 85, Arrays.asList(new Producto.Detalle("Demasiados", Nutricion.AZUCAR, 5000, Calidad.MALO), new Producto.Detalle("Demasiado pocos", Nutricion.WEBOS, 0, Calidad.REGULAR))),
            new Producto("Elao", "Masibon", R.drawable.ice_cream_cone_1274894_640, Calidad.MALO, null, 9, Arrays.asList(new Producto.Detalle("Pocos", Nutricion.NUECES, 10.05f, Calidad.EXCELENTE), new Producto.Detalle("Blip blup", Nutricion.SODIO, .0043f, Calidad.BUENO), new Producto.Detalle("AAAAAA", Nutricion.WEBOS, 10000000, Calidad.REGULAR), new Producto.Detalle("😂😂😂👌👌👌💯", Nutricion.HIERRO, 69, Calidad.EXCELENTE), new Producto.Detalle("10", Nutricion.VITAMINAS, 10, Calidad.REGULAR))),
            new Producto("Aceite de oliva virgen extra", "Marca", R.drawable.olive_oil_968657_640, Calidad.EXCELENTE, null, 97, Arrays.asList(new Producto.Detalle("Alto en", Nutricion.AZUCAR, 333.67f, Calidad.MALO), new Producto.Detalle("Bajo en", Nutricion.VENENO, -.5f, Calidad.EXCELENTE), new Producto.Detalle("Bajo en", Nutricion.FERTILIZANTE, 600, Calidad.MEDIOCRE), new Producto.Detalle("Casi sin", Nutricion.ENERGIA, 0.007f, Calidad.REGULAR))),
            new Producto("Verduras 100%", "100%", R.drawable.vegetables_1085063_640, Calidad.BUENO, null, 76, Arrays.asList(new Producto.Detalle("Un puñado de", Nutricion.VITAMINAS, 25, Calidad.BUENO))),
            new Producto("Manzana con libros", "Apple", R.drawable.apple_256261_640, Calidad.BUENO, null, 73, Arrays.asList(new Producto.Detalle("Bajo en", Nutricion.FERTILIZANTE, 35.75f, Calidad.BUENO), new Producto.Detalle("Hasta arriba de", Nutricion.AZUCAR, 500, Calidad.MALO), new Producto.Detalle("Así asá de", Nutricion.PROTEINAS, 0.05f, Calidad.REGULAR), new Producto.Detalle("Un poquito de", Nutricion.TACOS, .5f, Calidad.BUENO), new Producto.Detalle("Bastantes ", Nutricion.NUECES, 30, Calidad.EXCELENTE))),
            new Producto("Frutas del bosque", "Mercadona", R.drawable.dark_mood_food_2986532_640, Calidad.MEDIOCRE, null, 23, Arrays.asList(new Producto.Detalle("Un par de", Nutricion.NUECES, 2, Calidad.MALO), new Producto.Detalle("Alto en", Nutricion.PROTEINAS, 23, Calidad.EXCELENTE), new Producto.Detalle("Moderada", Nutricion.ENERGIA, 1500, Calidad.BUENO), new Producto.Detalle("Un poco de", Nutricion.SODIO, 9, Calidad.BUENO))),
            new Producto("Ingredientes para pasta", "Samsung", R.drawable.food_1932466_640, Calidad.EXCELENTE, null, 91, Arrays.asList(new Producto.Detalle("Alto en", Nutricion.AZUCAR, 100, Calidad.MEDIOCRE), new Producto.Detalle("Alto en", Nutricion.SODIO, 1290, Calidad.MALO), new Producto.Detalle("Algo de", Nutricion.AMIANTO, 0.02f, Calidad.BUENO))),
            new Producto("Tabla embutido", "Lidl", R.drawable.food_platter_2175326_640, Calidad.REGULAR, null, 49, Arrays.asList(new Producto.Detalle("Moderados", Nutricion.TACOS, 10, Calidad.EXCELENTE), new Producto.Detalle("Moderadamente", Nutricion.RAMEN, 1.6729f, Calidad.REGULAR), new Producto.Detalle("Moderados", Nutricion.NUECES, .77f, Calidad.MEDIOCRE), new Producto.Detalle("Una cantidad de", Nutricion.GASOLINA, 995, Calidad.BUENO))),
            new Producto("Ositos gominolas", "Haribo", R.drawable.gummibarchen_318362_640, Calidad.BUENO, null, 85, Arrays.asList(new Producto.Detalle("Demasiados", Nutricion.AZUCAR, 5000, Calidad.MALO), new Producto.Detalle("Demasiado pocos", Nutricion.WEBOS, 0, Calidad.REGULAR))),
            new Producto("Elao", "Masibon", R.drawable.ice_cream_cone_1274894_640, Calidad.MALO, null, 9, Arrays.asList(new Producto.Detalle("Pocos", Nutricion.NUECES, 10.05f, Calidad.EXCELENTE), new Producto.Detalle("Blip blup", Nutricion.SODIO, .0043f, Calidad.BUENO), new Producto.Detalle("AAAAAA", Nutricion.WEBOS, 10000000, Calidad.REGULAR), new Producto.Detalle("😂😂😂👌👌👌💯", Nutricion.HIERRO, 69, Calidad.EXCELENTE), new Producto.Detalle("10", Nutricion.VITAMINAS, 10, Calidad.REGULAR))),
            new Producto("Aceite de oliva virgen extra", "Marca", R.drawable.olive_oil_968657_640, Calidad.EXCELENTE, null, 97, Arrays.asList(new Producto.Detalle("Alto en", Nutricion.AZUCAR, 333.67f, Calidad.MALO), new Producto.Detalle("Bajo en", Nutricion.VENENO, -.5f, Calidad.EXCELENTE), new Producto.Detalle("Bajo en", Nutricion.FERTILIZANTE, 600, Calidad.MEDIOCRE), new Producto.Detalle("Casi sin", Nutricion.ENERGIA, 0.007f, Calidad.REGULAR))),
            new Producto("Verduras 100%", "100%", R.drawable.vegetables_1085063_640, Calidad.BUENO, null, 76, Arrays.asList(new Producto.Detalle("Un puñado de", Nutricion.VITAMINAS, 25, Calidad.BUENO))),new Producto("Manzana con libros", "Apple", R.drawable.apple_256261_640, Calidad.BUENO, null, 73, Arrays.asList(new Producto.Detalle("Bajo en", Nutricion.FERTILIZANTE, 35.75f, Calidad.BUENO), new Producto.Detalle("Hasta arriba de", Nutricion.AZUCAR, 500, Calidad.MALO), new Producto.Detalle("Así asá de", Nutricion.PROTEINAS, 0.05f, Calidad.REGULAR), new Producto.Detalle("Un poquito de", Nutricion.TACOS, .5f, Calidad.BUENO), new Producto.Detalle("Bastantes ", Nutricion.NUECES, 30, Calidad.EXCELENTE))),
            new Producto("Frutas del bosque", "Mercadona", R.drawable.dark_mood_food_2986532_640, Calidad.MEDIOCRE, null, 23, Arrays.asList(new Producto.Detalle("Un par de", Nutricion.NUECES, 2, Calidad.MALO), new Producto.Detalle("Alto en", Nutricion.PROTEINAS, 23, Calidad.EXCELENTE), new Producto.Detalle("Moderada", Nutricion.ENERGIA, 1500, Calidad.BUENO), new Producto.Detalle("Un poco de", Nutricion.SODIO, 9, Calidad.BUENO))),
            new Producto("Ingredientes para pasta", "Samsung", R.drawable.food_1932466_640, Calidad.EXCELENTE, null, 91, Arrays.asList(new Producto.Detalle("Alto en", Nutricion.AZUCAR, 100, Calidad.MEDIOCRE), new Producto.Detalle("Alto en", Nutricion.SODIO, 1290, Calidad.MALO), new Producto.Detalle("Algo de", Nutricion.AMIANTO, 0.02f, Calidad.BUENO))),
            new Producto("Tabla embutido", "Lidl", R.drawable.food_platter_2175326_640, Calidad.REGULAR, null, 49, Arrays.asList(new Producto.Detalle("Moderados", Nutricion.TACOS, 10, Calidad.EXCELENTE), new Producto.Detalle("Moderadamente", Nutricion.RAMEN, 1.6729f, Calidad.REGULAR), new Producto.Detalle("Moderados", Nutricion.NUECES, .77f, Calidad.MEDIOCRE), new Producto.Detalle("Una cantidad de", Nutricion.GASOLINA, 995, Calidad.BUENO))),
            new Producto("Ositos gominolas", "Haribo", R.drawable.gummibarchen_318362_640, Calidad.BUENO, null, 85, Arrays.asList(new Producto.Detalle("Demasiados", Nutricion.AZUCAR, 5000, Calidad.MALO), new Producto.Detalle("Demasiado pocos", Nutricion.WEBOS, 0, Calidad.REGULAR))),
            new Producto("Elao", "Masibon", R.drawable.ice_cream_cone_1274894_640, Calidad.MALO, null, 9, Arrays.asList(new Producto.Detalle("Pocos", Nutricion.NUECES, 10.05f, Calidad.EXCELENTE), new Producto.Detalle("Blip blup", Nutricion.SODIO, .0043f, Calidad.BUENO), new Producto.Detalle("AAAAAA", Nutricion.WEBOS, 10000000, Calidad.REGULAR), new Producto.Detalle("😂😂😂👌👌👌💯", Nutricion.HIERRO, 69, Calidad.EXCELENTE), new Producto.Detalle("10", Nutricion.VITAMINAS, 10, Calidad.REGULAR))),
            new Producto("Aceite de oliva virgen extra", "Marca", R.drawable.olive_oil_968657_640, Calidad.EXCELENTE, null, 97, Arrays.asList(new Producto.Detalle("Alto en", Nutricion.AZUCAR, 333.67f, Calidad.MALO), new Producto.Detalle("Bajo en", Nutricion.VENENO, -.5f, Calidad.EXCELENTE), new Producto.Detalle("Bajo en", Nutricion.FERTILIZANTE, 600, Calidad.MEDIOCRE), new Producto.Detalle("Casi sin", Nutricion.ENERGIA, 0.007f, Calidad.REGULAR))),
            new Producto("Verduras 100%", "100%", R.drawable.vegetables_1085063_640, Calidad.BUENO, null, 76, Arrays.asList(new Producto.Detalle("Un puñado de", Nutricion.VITAMINAS, 25, Calidad.BUENO))),new Producto("Manzana con libros", "Apple", R.drawable.apple_256261_640, Calidad.BUENO, null, 73, Arrays.asList(new Producto.Detalle("Bajo en", Nutricion.FERTILIZANTE, 35.75f, Calidad.BUENO), new Producto.Detalle("Hasta arriba de", Nutricion.AZUCAR, 500, Calidad.MALO), new Producto.Detalle("Así asá de", Nutricion.PROTEINAS, 0.05f, Calidad.REGULAR), new Producto.Detalle("Un poquito de", Nutricion.TACOS, .5f, Calidad.BUENO), new Producto.Detalle("Bastantes ", Nutricion.NUECES, 30, Calidad.EXCELENTE))),
            new Producto("Frutas del bosque", "Mercadona", R.drawable.dark_mood_food_2986532_640, Calidad.MEDIOCRE, null, 23, Arrays.asList(new Producto.Detalle("Un par de", Nutricion.NUECES, 2, Calidad.MALO), new Producto.Detalle("Alto en", Nutricion.PROTEINAS, 23, Calidad.EXCELENTE), new Producto.Detalle("Moderada", Nutricion.ENERGIA, 1500, Calidad.BUENO), new Producto.Detalle("Un poco de", Nutricion.SODIO, 9, Calidad.BUENO))),
            new Producto("Ingredientes para pasta", "Samsung", R.drawable.food_1932466_640, Calidad.EXCELENTE, null, 91, Arrays.asList(new Producto.Detalle("Alto en", Nutricion.AZUCAR, 100, Calidad.MEDIOCRE), new Producto.Detalle("Alto en", Nutricion.SODIO, 1290, Calidad.MALO), new Producto.Detalle("Algo de", Nutricion.AMIANTO, 0.02f, Calidad.BUENO))),
            new Producto("Tabla embutido", "Lidl", R.drawable.food_platter_2175326_640, Calidad.REGULAR, null, 49, Arrays.asList(new Producto.Detalle("Moderados", Nutricion.TACOS, 10, Calidad.EXCELENTE), new Producto.Detalle("Moderadamente", Nutricion.RAMEN, 1.6729f, Calidad.REGULAR), new Producto.Detalle("Moderados", Nutricion.NUECES, .77f, Calidad.MEDIOCRE), new Producto.Detalle("Una cantidad de", Nutricion.GASOLINA, 995, Calidad.BUENO))),
            new Producto("Ositos gominolas", "Haribo", R.drawable.gummibarchen_318362_640, Calidad.BUENO, null, 85, Arrays.asList(new Producto.Detalle("Demasiados", Nutricion.AZUCAR, 5000, Calidad.MALO), new Producto.Detalle("Demasiado pocos", Nutricion.WEBOS, 0, Calidad.REGULAR))),
            new Producto("Elao", "Masibon", R.drawable.ice_cream_cone_1274894_640, Calidad.MALO, null, 9, Arrays.asList(new Producto.Detalle("Pocos", Nutricion.NUECES, 10.05f, Calidad.EXCELENTE), new Producto.Detalle("Blip blup", Nutricion.SODIO, .0043f, Calidad.BUENO), new Producto.Detalle("AAAAAA", Nutricion.WEBOS, 10000000, Calidad.REGULAR), new Producto.Detalle("😂😂😂👌👌👌💯", Nutricion.HIERRO, 69, Calidad.EXCELENTE), new Producto.Detalle("10", Nutricion.VITAMINAS, 10, Calidad.REGULAR))),
            new Producto("Aceite de oliva virgen extra", "Marca", R.drawable.olive_oil_968657_640, Calidad.EXCELENTE, null, 97, Arrays.asList(new Producto.Detalle("Alto en", Nutricion.AZUCAR, 333.67f, Calidad.MALO), new Producto.Detalle("Bajo en", Nutricion.VENENO, -.5f, Calidad.EXCELENTE), new Producto.Detalle("Bajo en", Nutricion.FERTILIZANTE, 600, Calidad.MEDIOCRE), new Producto.Detalle("Casi sin", Nutricion.ENERGIA, 0.007f, Calidad.REGULAR))),
            new Producto("Verduras 100%", "100%", R.drawable.vegetables_1085063_640, Calidad.BUENO, null, 76, Arrays.asList(new Producto.Detalle("Un puñado de", Nutricion.VITAMINAS, 25, Calidad.BUENO))),new Producto("Manzana con libros", "Apple", R.drawable.apple_256261_640, Calidad.BUENO, null, 73, Arrays.asList(new Producto.Detalle("Bajo en", Nutricion.FERTILIZANTE, 35.75f, Calidad.BUENO), new Producto.Detalle("Hasta arriba de", Nutricion.AZUCAR, 500, Calidad.MALO), new Producto.Detalle("Así asá de", Nutricion.PROTEINAS, 0.05f, Calidad.REGULAR), new Producto.Detalle("Un poquito de", Nutricion.TACOS, .5f, Calidad.BUENO), new Producto.Detalle("Bastantes ", Nutricion.NUECES, 30, Calidad.EXCELENTE))),
            new Producto("Frutas del bosque", "Mercadona", R.drawable.dark_mood_food_2986532_640, Calidad.MEDIOCRE, null, 23, Arrays.asList(new Producto.Detalle("Un par de", Nutricion.NUECES, 2, Calidad.MALO), new Producto.Detalle("Alto en", Nutricion.PROTEINAS, 23, Calidad.EXCELENTE), new Producto.Detalle("Moderada", Nutricion.ENERGIA, 1500, Calidad.BUENO), new Producto.Detalle("Un poco de", Nutricion.SODIO, 9, Calidad.BUENO))),
            new Producto("Ingredientes para pasta", "Samsung", R.drawable.food_1932466_640, Calidad.EXCELENTE, null, 91, Arrays.asList(new Producto.Detalle("Alto en", Nutricion.AZUCAR, 100, Calidad.MEDIOCRE), new Producto.Detalle("Alto en", Nutricion.SODIO, 1290, Calidad.MALO), new Producto.Detalle("Algo de", Nutricion.AMIANTO, 0.02f, Calidad.BUENO))),
            new Producto("Tabla embutido", "Lidl", R.drawable.food_platter_2175326_640, Calidad.REGULAR, null, 49, Arrays.asList(new Producto.Detalle("Moderados", Nutricion.TACOS, 10, Calidad.EXCELENTE), new Producto.Detalle("Moderadamente", Nutricion.RAMEN, 1.6729f, Calidad.REGULAR), new Producto.Detalle("Moderados", Nutricion.NUECES, .77f, Calidad.MEDIOCRE), new Producto.Detalle("Una cantidad de", Nutricion.GASOLINA, 995, Calidad.BUENO))),
            new Producto("Ositos gominolas", "Haribo", R.drawable.gummibarchen_318362_640, Calidad.BUENO, null, 85, Arrays.asList(new Producto.Detalle("Demasiados", Nutricion.AZUCAR, 5000, Calidad.MALO), new Producto.Detalle("Demasiado pocos", Nutricion.WEBOS, 0, Calidad.REGULAR))),
            new Producto("Elao", "Masibon", R.drawable.ice_cream_cone_1274894_640, Calidad.MALO, null, 9, Arrays.asList(new Producto.Detalle("Pocos", Nutricion.NUECES, 10.05f, Calidad.EXCELENTE), new Producto.Detalle("Blip blup", Nutricion.SODIO, .0043f, Calidad.BUENO), new Producto.Detalle("AAAAAA", Nutricion.WEBOS, 10000000, Calidad.REGULAR), new Producto.Detalle("😂😂😂👌👌👌💯", Nutricion.HIERRO, 69, Calidad.EXCELENTE), new Producto.Detalle("10", Nutricion.VITAMINAS, 10, Calidad.REGULAR))),
            new Producto("Aceite de oliva virgen extra", "Marca", R.drawable.olive_oil_968657_640, Calidad.EXCELENTE, null, 97, Arrays.asList(new Producto.Detalle("Alto en", Nutricion.AZUCAR, 333.67f, Calidad.MALO), new Producto.Detalle("Bajo en", Nutricion.VENENO, -.5f, Calidad.EXCELENTE), new Producto.Detalle("Bajo en", Nutricion.FERTILIZANTE, 600, Calidad.MEDIOCRE), new Producto.Detalle("Casi sin", Nutricion.ENERGIA, 0.007f, Calidad.REGULAR))),
            new Producto("Verduras 100%", "100%", R.drawable.vegetables_1085063_640, Calidad.BUENO, null, 76, Arrays.asList(new Producto.Detalle("Un puñado de", Nutricion.VITAMINAS, 25, Calidad.BUENO)))
    };

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        lista = findViewById(R.id.recyclerView);
        lista.setAdapter(new AdaptadorDeProductos(this, productos));
        lista.setLayoutManager(new LinearLayoutManager(this));
    }
}